site_name: ele blog
site_url: https://eeeleeeeee.github.io/blog/

theme:
  name: material
  font:
    text: Noto Sans TC
    code: JetBrains Mono
  icon:
    logo: material/elephant
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.follow

plugins:
  - search
  - blog:
      archive: false
      post_url_format: "{slug}"

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
