site_name: ele blog
site_url: https://eeeleeeeee.github.io/blog/
copyright: Copyright &copy; <span class="copyright-year">2026</span> ele

extra:
  generator: false

extra_javascript:
  - javascripts/copyright-year.js

theme:
  name: material
  font:
    text: Noto Sans TC
    code: JetBrains Mono
  icon:
    logo: material/elephant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切換成深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切換成淺色模式
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - search.highlight
    - search.suggest
    - navigation.path

plugins:
  - search
  - heti
  - glightbox
  - mermaid2
  - blog:
      archive: false
      post_url_format: "{slug}"
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    anchors: warn

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
